### ISSUE TITLE
It is working for .NET Core 3.1 ?

### ISSUE THREAD

**Issue by ignatandrei** [kzu/ThisAssembly#1]
just asking if it is working for .NET Core 3.1
( I can reference the nuget ... - but it does not compile 
 Console.WriteLine(ThisAssembly.Info.Configuration);

**Comment by kzu** [comment]
Nope, this uses Roslyn source generators, which is a feature included in .net5 SDK and VS 16.8 previews

**Comment by kzu** [comment]
The next release will check this via targets so it's less surprising that it doesn't work

**Comment by kzu** [comment]
Hm... [this check](https://github.com/kzu/ThisAssembly/blob/main/src/ThisAssembly.Prerequisites/ThisAssembly.Prerequisites.targets#L4-L7) should already be shipping in the latest 1.0.0-alpha release. Are you not seeing that build error automatically when using .NET Core 3.1?

**Comment by ignatandrei** [comment]
1>CSC : warning CS8032: An instance of analyzer ThisAssembly.AssemblyInfoGenerator cannot be created from C:\Users\aignat\.nuget\packages\thisassembly.assemblyinfo\0.10.6\analyzers\netstandard2.0\ThisAssembly.AssemblyInfo.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..


I have added reference to 
  <PackageReference Include="Microsoft.CodeAnalysis" Version="3.8.0-3.final" />
  <PackageReference Include="ThisAssembly.AssemblyInfo" Version="0.10.6" />


But it gives the same error

**Comment by kzu** [comment]
Old version. Use ThisAssembly.* Version 1.0.0-alpha plz. The one you're referencing isn't even listed anymore :)

**Comment by ignatandrei** [comment]
Now the error is more explicit 👍 

 ThisAssembly requires MSBuild 16.8+ or .NET SDK 5.0+.

Waiting for .NET 5 in one month or so ;-)
Thanks
