### ISSUE TITLE
New ThisAssembly.Info release with new added attributes?

### ISSUE THREAD

**Issue by atifaziz** [kzu/ThisAssembly#10]
Thanks for this great source generator, @kzu! It's a fantastically simple idea yet helps a great deal.

I was just adding ThisAssembly.Info to one of my projects when I realised that information from some attributes like `AssemblyCopyrightAttribute` is missing. Looking at the sources, I see they were in added in  4f7b47639afaee56064af54c5fc5cd2c09ffb4be. I guess the change hasn't been released yet? Any chance to get that soon, even if it's just for ThisAssembly.Info?

**Comment by kzu** [comment]
Thanks @atifaziz for your comments!

Just created the final 1.0.0 at https://github.com/kzu/ThisAssembly/releases/tag/v1.0.0. Should be up on nuget in just a bit.

**Comment by atifaziz** [comment]
Thank you, sir! 🙏🏼
