### ISSUE TITLE
Included in reference list - add 'csharp-sourcegenerator' repo topic?

### ISSUE THREAD

**Issue by amis92** [kzu/ThisAssembly#5]
Hi,

I've included your repository in my personal [C# Source Generators list](https://github.com/amis92/csharp-source-generators) to help gather these kind of projects in one place and hopefully under single umbrella, thus I propose to add the `csharp-sourcegenerator` topic to this repository to help with visibility.

I hope you're okay with this. If you happen to know other generator projects, I'll be happy to enlist those in my list as well.

Thanks!

**Comment by kzu** [comment]
Done, https://github.com/kzu/SmallSharp/ also uses source generators for entirely different means :) (it generates launchsettings.json!)

**Comment by kzu** [comment]
This is an interesting one too https://github.com/kzu/avatar (static dynamic proxies, LoL)
